// src/features/gallery/ImageGallery.tsx
import { useState, useMemo, useCallback, useEffect } from 'react'
import { TransformWrapper, TransformComponent } from 'react-zoom-pan-pinch'
import { Button } from '@/shared/ui/button'
import { ScrollArea } from '@/shared/ui/scroll-area'
import { Badge } from '@/shared/ui/badge'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/shared/ui/select'
import { Separator } from '@/shared/ui/separator'
import { useDataStore, useFilteredRecords } from '@/features/data'
import { getProxiedUrl, getThumbnailUrl } from '@/shared/lib/imageProxy'
import {
  X,
  ChevronLeft,
  ChevronRight,
  ZoomIn,
  ZoomOut,
  RotateCcw,
  MapPin,
  Calendar,
  Dna,
  Image as ImageIcon,
  AlertCircle,
} from 'lucide-react'
import type { Record as DataRecord } from '@/features/data/types'

// Status colors matching the rest of the app
const STATUS_COLORS: { [key: string]: string } = {
  Sequenced: '#3b82f6',
  'Tissue Available': '#10b981',
  'Preserved Specimen': '#f59e0b',
  Published: '#a855f7',
}

interface ImageGalleryProps {
  open: boolean
  onClose: () => void
  initialSpecimenId?: string
}

interface GroupedBySpecies {
  [species: string]: {
    count: number
    subspecies: {
      [subspecies: string]: {
        count: number
        individuals: DataRecord[]
      }
    }
  }
}

function groupBySpecies(records: DataRecord[]): GroupedBySpecies {
  const grouped: GroupedBySpecies = {}

  for (const record of records) {
    if (!record.image_url) continue

    const species = record.scientific_name || 'Unknown'
    const subspecies = record.subspecies || 'No subspecies'

    if (!grouped[species]) {
      grouped[species] = { count: 0, subspecies: {} }
    }

    if (!grouped[species].subspecies[subspecies]) {
      grouped[species].subspecies[subspecies] = { count: 0, individuals: [] }
    }

    grouped[species].count++
    grouped[species].subspecies[subspecies].count++
    grouped[species].subspecies[subspecies].individuals.push(record)
  }

  return grouped
}

export function ImageGallery({ open, onClose, initialSpecimenId }: ImageGalleryProps) {
  const filteredRecords = useFilteredRecords()
  const setSelectedPoint = useDataStore((s) => s.setSelectedPoint)

  // Get all specimens with images
  const specimensWithImages = useMemo(
    () => filteredRecords.filter((r) => r.image_url),
    [filteredRecords]
  )

  // Group by species
  const groupedBySpecies = useMemo(
    () => groupBySpecies(specimensWithImages),
    [specimensWithImages]
  )

  // Species list sorted by count
  const speciesList = useMemo(
    () =>
      Object.entries(groupedBySpecies)
        .map(([species, data]) => ({ species, count: data.count }))
        .sort((a, b) => b.count - a.count),
    [groupedBySpecies]
  )

  // State
  const [currentIndex, setCurrentIndex] = useState(0)
  const [selectedSpecies, setSelectedSpecies] = useState<string | null>(null)
  const [selectedSubspecies, setSelectedSubspecies] = useState<string | null>(null)
  const [isLoading, setIsLoading] = useState(true)
  const [loadError, setLoadError] = useState(false)
  const [zoomLevel, setZoomLevel] = useState(1)

  // Initialize from initial specimen
  useEffect(() => {
    if (!open) return

    if (initialSpecimenId) {
      const idx = specimensWithImages.findIndex((s) => s.id === initialSpecimenId)
      if (idx >= 0) {
        setCurrentIndex(idx)
        const specimen = specimensWithImages[idx]
        setSelectedSpecies(specimen.scientific_name)
        setSelectedSubspecies(specimen.subspecies)
      }
    } else if (specimensWithImages.length > 0) {
      setCurrentIndex(0)
      const first = specimensWithImages[0]
      setSelectedSpecies(first.scientific_name)
      setSelectedSubspecies(first.subspecies)
    }
  }, [open, initialSpecimenId, specimensWithImages])

  // Subspecies list for selected species
  const subspeciesList = useMemo(() => {
    if (!selectedSpecies || !groupedBySpecies[selectedSpecies]) return []
    return Object.entries(groupedBySpecies[selectedSpecies].subspecies)
      .map(([name, data]) => ({ name, count: data.count }))
      .sort((a, b) => b.count - a.count)
  }, [selectedSpecies, groupedBySpecies])

  // Individuals list for selected species/subspecies
  const individualsList = useMemo(() => {
    if (!selectedSpecies || !groupedBySpecies[selectedSpecies]) {
      return specimensWithImages
    }

    const speciesGroup = groupedBySpecies[selectedSpecies]
    if (selectedSubspecies && speciesGroup.subspecies[selectedSubspecies]) {
      return speciesGroup.subspecies[selectedSubspecies].individuals
    }

    return Object.values(speciesGroup.subspecies).flatMap((s) => s.individuals)
  }, [selectedSpecies, selectedSubspecies, groupedBySpecies, specimensWithImages])

  const currentSpecimen = specimensWithImages[currentIndex] || null

  // Navigation
  const hasPrev = currentIndex > 0
  const hasNext = currentIndex < specimensWithImages.length - 1

  const goToPrev = useCallback(() => {
    if (hasPrev) {
      setCurrentIndex((i) => i - 1)
      setIsLoading(true)
      setLoadError(false)
    }
  }, [hasPrev])

  const goToNext = useCallback(() => {
    if (hasNext) {
      setCurrentIndex((i) => i + 1)
      setIsLoading(true)
      setLoadError(false)
    }
  }, [hasNext])

  const selectSpecimen = useCallback(
    (id: string) => {
      const idx = specimensWithImages.findIndex((s) => s.id === id)
      if (idx >= 0) {
        setCurrentIndex(idx)
        setIsLoading(true)
        setLoadError(false)
      }
    },
    [specimensWithImages]
  )

  // Update selection when current specimen changes
  useEffect(() => {
    if (currentSpecimen) {
      setSelectedSpecies(currentSpecimen.scientific_name)
      setSelectedSubspecies(currentSpecimen.subspecies)
    }
  }, [currentSpecimen])

  // Keyboard navigation
  useEffect(() => {
    if (!open) return

    const handleKeyDown = (e: KeyboardEvent) => {
      switch (e.key) {
        case 'ArrowLeft':
          goToPrev()
          break
        case 'ArrowRight':
          goToNext()
          break
        case 'Escape':
          onClose()
          break
      }
    }

    document.addEventListener('keydown', handleKeyDown)
    return () => document.removeEventListener('keydown', handleKeyDown)
  }, [open, goToPrev, goToNext, onClose])

  // View on map
  const viewOnMap = useCallback(() => {
    if (currentSpecimen) {
      setSelectedPoint(currentSpecimen.id)
      onClose()
    }
  }, [currentSpecimen, setSelectedPoint, onClose])

  if (!open) return null

  // Empty state
  if (specimensWithImages.length === 0) {
    return (
      <div className="fixed inset-0 z-[100] flex flex-col items-center justify-center bg-black/95">
        <Button
          variant="ghost"
          size="icon"
          className="absolute right-4 top-4 rounded-full bg-white/10 text-white hover:bg-white/20"
          onClick={onClose}
        >
          <X className="h-6 w-6" />
        </Button>
        <ImageIcon className="mb-5 h-20 w-20 opacity-50 text-muted-foreground" />
        <h3 className="mb-2.5 text-2xl text-secondary-foreground">No Images Available</h3>
        <p className="mb-6 text-muted-foreground">
          No specimens in the current filter have images attached.
        </p>
        <Button onClick={onClose}>Back to Map</Button>
      </div>
    )
  }

  return (
    <div className="fixed inset-0 z-[100] flex flex-col bg-black/95">
      {/* Close button */}
      <Button
        variant="ghost"
        size="icon"
        className="absolute right-4 top-4 z-10 h-11 w-11 rounded-full bg-white/10 text-white hover:bg-white/20"
        onClick={onClose}
      >
        <X className="h-6 w-6" />
      </Button>

      <div className="flex flex-1 overflow-hidden">
        {/* Sidebar */}
        <div className="flex w-56 flex-shrink-0 flex-col gap-3 border-r border-border bg-background p-4">
          <ScrollArea className="flex-1">
            <div className="flex flex-col gap-3">
              {/* Species selector */}
              <div>
                <div className="mb-1.5 flex items-center gap-1.5">
                  <Badge variant="secondary" className="text-primary">
                    {speciesList.length}
                  </Badge>
                  <span className="text-xs uppercase tracking-wider text-muted-foreground">
                    Species
                  </span>
                </div>
                <Select
                  value={selectedSpecies || ''}
                  onValueChange={(value) => {
                    setSelectedSpecies(value)
                    const subspeciesNames = Object.keys(
                      groupedBySpecies[value]?.subspecies || {}
                    )
                    setSelectedSubspecies(subspeciesNames[0] || null)
                  }}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select species" />
                  </SelectTrigger>
                  <SelectContent>
                    {speciesList.map((sp) => (
                      <SelectItem key={sp.species} value={sp.species}>
                        <span className="italic">{sp.species}</span>
                        <span className="ml-2 text-muted-foreground">({sp.count})</span>
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {/* Subspecies selector */}
              {subspeciesList.length > 0 && (
                <div>
                  <div className="mb-1.5 flex items-center gap-1.5">
                    <Badge variant="secondary" className="text-primary">
                      {subspeciesList.length}
                    </Badge>
                    <span className="text-xs uppercase tracking-wider text-muted-foreground">
                      Subspecies
                    </span>
                  </div>
                  <Select
                    value={selectedSubspecies || ''}
                    onValueChange={setSelectedSubspecies}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Select subspecies" />
                    </SelectTrigger>
                    <SelectContent>
                      {subspeciesList.map((ssp) => (
                        <SelectItem key={ssp.name} value={ssp.name}>
                          <span className="italic">{ssp.name}</span>
                          <span className="ml-2 text-muted-foreground">({ssp.count})</span>
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              )}

              {/* Individual selector */}
              <div>
                <div className="mb-1.5 flex items-center gap-1.5">
                  <Badge variant="secondary" className="text-primary">
                    {individualsList.length}
                  </Badge>
                  <span className="text-xs uppercase tracking-wider text-muted-foreground">
                    Individuals
                  </span>
                </div>
                <Select
                  value={currentSpecimen?.id || ''}
                  onValueChange={selectSpecimen}
                >
                  <SelectTrigger className="font-mono">
                    <SelectValue placeholder="Select individual" />
                  </SelectTrigger>
                  <SelectContent>
                    {individualsList.map((ind) => (
                      <SelectItem key={ind.id} value={ind.id} className="font-mono">
                        {ind.id}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <Separator />

              {/* Current specimen details */}
              {currentSpecimen && (
                <div className="space-y-2 text-xs">
                  <div>
                    <span className="text-muted-foreground">ID</span>
                    <p className="font-mono text-primary">{currentSpecimen.id}</p>
                  </div>

                  {currentSpecimen.observation_date && (
                    <div className="flex items-center gap-2">
                      <Calendar className="h-3.5 w-3.5 text-muted-foreground" />
                      <span>{currentSpecimen.observation_date}</span>
                    </div>
                  )}

                  {currentSpecimen.collection_location && (
                    <div className="flex items-start gap-2">
                      <MapPin className="mt-0.5 h-3.5 w-3.5 text-muted-foreground" />
                      <span>{currentSpecimen.collection_location}</span>
                    </div>
                  )}

                  {currentSpecimen.sequencing_status && (
                    <div className="flex items-center gap-2">
                      <Dna className="h-3.5 w-3.5 text-muted-foreground" />
                      <div className="flex items-center gap-1.5">
                        <span
                          className="h-2 w-2 rounded-full"
                          style={{
                            backgroundColor:
                              STATUS_COLORS[currentSpecimen.sequencing_status] || '#6b7280',
                          }}
                        />
                        <span>{currentSpecimen.sequencing_status}</span>
                      </div>
                    </div>
                  )}

                  <div>
                    <span className="text-muted-foreground">Source</span>
                    <p>{currentSpecimen.source}</p>
                  </div>

                  <Button
                    variant="outline"
                    size="sm"
                    className="mt-2 w-full gap-2"
                    onClick={viewOnMap}
                  >
                    <MapPin className="h-4 w-4" />
                    View on Map
                  </Button>
                </div>
              )}

              <Separator />

              {/* Summary */}
              <div className="rounded-md border border-primary/15 bg-primary/5 p-2.5">
                <div className="mb-2 text-xs uppercase tracking-wider text-primary">
                  Summary
                </div>
                <div className="space-y-1 text-xs">
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Species:</span>
                    <span className="font-semibold text-primary">{speciesList.length}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">With images:</span>
                    <span className="font-semibold text-primary">
                      {specimensWithImages.length}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Total filtered:</span>
                    <span className="font-semibold text-primary">
                      {filteredRecords.length}
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </ScrollArea>
        </div>

        {/* Image viewer */}
        <div className="relative flex flex-1 flex-col">
          <div className="flex flex-1 items-center justify-center overflow-hidden">
            {isLoading && !loadError && (
              <div className="absolute h-12 w-12 animate-spin rounded-full border-4 border-white/10 border-t-primary" />
            )}

            {loadError && (
              <div className="flex flex-col items-center text-muted-foreground">
                <AlertCircle className="mb-3 h-14 w-14" />
                <p>Failed to load image</p>
              </div>
            )}

            {currentSpecimen?.image_url && (
              <TransformWrapper
                initialScale={1}
                minScale={0.5}
                maxScale={5}
                centerOnInit
                onTransformed={(_, state) => setZoomLevel(state.scale)}
              >
                {({ zoomIn, zoomOut, resetTransform }) => (
                  <>
                    <TransformComponent
                      wrapperClass="!w-full !h-full"
                      contentClass="!w-full !h-full flex items-center justify-center"
                    >
                      <img
                        src={getProxiedUrl(currentSpecimen.image_url)}
                        alt={currentSpecimen.scientific_name}
                        className={`max-h-full max-w-[90%] object-contain ${
                          isLoading ? 'invisible' : 'visible'
                        }`}
                        onLoad={() => {
                          setIsLoading(false)
                          setLoadError(false)
                        }}
                        onError={() => {
                          setIsLoading(false)
                          setLoadError(true)
                        }}
                        draggable={false}
                      />
                    </TransformComponent>

                    {/* Zoom controls */}
                    <div className="absolute bottom-5 left-1/2 z-10 flex -translate-x-1/2 items-center gap-2 rounded-lg bg-black/60 px-3 py-2 backdrop-blur-sm">
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-9 w-9 bg-white/10 text-white hover:bg-white/20 disabled:opacity-30"
                        onClick={() => zoomOut()}
                        disabled={zoomLevel <= 0.5}
                      >
                        <ZoomOut className="h-5 w-5" />
                      </Button>
                      <span className="min-w-[50px] text-center text-sm tabular-nums text-muted-foreground">
                        {Math.round(zoomLevel * 100)}%
                      </span>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-9 w-9 bg-white/10 text-white hover:bg-white/20 disabled:opacity-30"
                        onClick={() => zoomIn()}
                        disabled={zoomLevel >= 5}
                      >
                        <ZoomIn className="h-5 w-5" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="sm"
                        className="h-9 bg-white/10 px-3 text-white hover:bg-white/20 disabled:opacity-30"
                        onClick={() => resetTransform()}
                        disabled={zoomLevel <= 1.05}
                      >
                        <RotateCcw className="mr-1 h-4 w-4" />
                        Reset
                      </Button>
                    </div>
                  </>
                )}
              </TransformWrapper>
            )}
          </div>

          {/* Navigation buttons */}
          <button
            className="absolute left-0 top-1/2 z-5 flex h-20 w-12 -translate-y-1/2 items-center justify-center rounded-r-lg bg-black/40 text-white hover:bg-black/60 disabled:cursor-not-allowed disabled:opacity-30"
            disabled={!hasPrev}
            onClick={goToPrev}
          >
            <ChevronLeft className="h-7 w-7" />
          </button>
          <button
            className="absolute right-0 top-1/2 z-5 flex h-20 w-12 -translate-y-1/2 items-center justify-center rounded-l-lg bg-black/40 text-white hover:bg-black/60 disabled:cursor-not-allowed disabled:opacity-30"
            disabled={!hasNext}
            onClick={goToNext}
          >
            <ChevronRight className="h-7 w-7" />
          </button>

          {/* Counter */}
          <div className="absolute bottom-5 right-5 z-5 rounded-md bg-black/60 px-3 py-1.5 text-sm tabular-nums text-muted-foreground">
            {currentIndex + 1} / {specimensWithImages.length}
          </div>
        </div>
      </div>

      {/* Thumbnail strip */}
      {specimensWithImages.length > 1 && (
        <div className="flex h-28 overflow-x-auto border-t border-white/10 bg-black/70">
          <div className="flex gap-1 p-2">
            {specimensWithImages.map((specimen, idx) => (
              <button
                key={specimen.id}
                className={`h-20 w-20 flex-shrink-0 overflow-hidden rounded border-2 transition-all hover:border-white/40 ${
                  currentIndex === idx
                    ? 'border-primary shadow-[0_0_8px_rgba(74,222,128,0.5)]'
                    : 'border-transparent'
                }`}
                onClick={() => selectSpecimen(specimen.id)}
                title={specimen.id}
              >
                <img
                  src={getThumbnailUrl(specimen.image_url)}
                    alt={specimen.id}
                    loading="lazy"
                    className="h-full w-full object-cover"
                />
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}

// src/components/ImageGallery.vue
<script setup>
import { ref, computed, onMounted, onUnmounted, watch } from 'vue'
import { useDataStore } from '../stores/data'

const store = useDataStore()
const emit = defineEmits(['close'])

// Gallery state
const currentIndex = ref(0)
const isZoomed = ref(false)
const zoomLevel = ref(1)
const panX = ref(0)
const panY = ref(0)
const isLoading = ref(true)
const loadError = ref(false)

// Image container ref
const imageContainer = ref(null)
const imageEl = ref(null)

// Get specimens with images
const specimensWithImages = computed(() => {
  const geo = store.filteredGeoJSON
  if (!geo || !geo.features) return []
  return geo.features
    .filter(f => f.properties?.image_url)
    .map(f => f.properties)
})

// Current specimen
const currentSpecimen = computed(() => {
  return specimensWithImages.value[currentIndex.value] || null
})

// Navigation
const hasPrev = computed(() => currentIndex.value > 0)
const hasNext = computed(() => currentIndex.value < specimensWithImages.value.length - 1)

const goToPrev = () => {
  if (hasPrev.value) {
    currentIndex.value--
    resetView()
  }
}

const goToNext = () => {
  if (hasNext.value) {
    currentIndex.value++
    resetView()
  }
}

const goToIndex = (idx) => {
  currentIndex.value = idx
  resetView()
}

// Reset view state
const resetView = () => {
  isZoomed.value = false
  zoomLevel.value = 1
  panX.value = 0
  panY.value = 0
  isLoading.value = true
  loadError.value = false
}

// Image loaded handler
const onImageLoad = () => {
  isLoading.value = false
  loadError.value = false
}

const onImageError = () => {
  isLoading.value = false
  loadError.value = true
}

// Zoom controls
const zoomIn = () => {
  if (zoomLevel.value < 4) {
    zoomLevel.value = Math.min(4, zoomLevel.value * 1.5)
    isZoomed.value = zoomLevel.value > 1
  }
}

const zoomOut = () => {
  if (zoomLevel.value > 1) {
    zoomLevel.value = Math.max(1, zoomLevel.value / 1.5)
    isZoomed.value = zoomLevel.value > 1
    if (zoomLevel.value === 1) {
      panX.value = 0
      panY.value = 0
    }
  }
}

const toggleZoom = () => {
  if (isZoomed.value) {
    resetView()
  } else {
    zoomLevel.value = 2
    isZoomed.value = true
  }
}

// Pan handling
let isPanning = false
let startX = 0
let startY = 0
let startPanX = 0
let startPanY = 0

const onMouseDown = (e) => {
  if (!isZoomed.value) return
  isPanning = true
  startX = e.clientX
  startY = e.clientY
  startPanX = panX.value
  startPanY = panY.value
  e.preventDefault()
}

const onMouseMove = (e) => {
  if (!isPanning) return
  const dx = e.clientX - startX
  const dy = e.clientY - startY
  panX.value = startPanX + dx
  panY.value = startPanY + dy
}

const onMouseUp = () => {
  isPanning = false
}

// Touch handling
let touchStartDist = 0
let touchStartZoom = 1

const onTouchStart = (e) => {
  if (e.touches.length === 2) {
    // Pinch zoom start
    const dx = e.touches[0].clientX - e.touches[1].clientX
    const dy = e.touches[0].clientY - e.touches[1].clientY
    touchStartDist = Math.sqrt(dx * dx + dy * dy)
    touchStartZoom = zoomLevel.value
  } else if (e.touches.length === 1 && isZoomed.value) {
    // Pan start
    isPanning = true
    startX = e.touches[0].clientX
    startY = e.touches[0].clientY
    startPanX = panX.value
    startPanY = panY.value
  }
}

const onTouchMove = (e) => {
  if (e.touches.length === 2) {
    // Pinch zoom
    const dx = e.touches[0].clientX - e.touches[1].clientX
    const dy = e.touches[0].clientY - e.touches[1].clientY
    const dist = Math.sqrt(dx * dx + dy * dy)
    const scale = dist / touchStartDist
    zoomLevel.value = Math.max(1, Math.min(4, touchStartZoom * scale))
    isZoomed.value = zoomLevel.value > 1
    e.preventDefault()
  } else if (e.touches.length === 1 && isPanning) {
    // Pan
    const dx = e.touches[0].clientX - startX
    const dy = e.touches[0].clientY - startY
    panX.value = startPanX + dx
    panY.value = startPanY + dy
    e.preventDefault()
  }
}

const onTouchEnd = () => {
  isPanning = false
}

// Wheel zoom
const onWheel = (e) => {
  e.preventDefault()
  if (e.deltaY < 0) {
    zoomIn()
  } else {
    zoomOut()
  }
}

// Keyboard navigation
const onKeyDown = (e) => {
  switch (e.key) {
    case 'ArrowLeft':
      goToPrev()
      break
    case 'ArrowRight':
      goToNext()
      break
    case 'Escape':
      if (isZoomed.value) {
        resetView()
      } else {
        emit('close')
      }
      break
    case '+':
    case '=':
      zoomIn()
      break
    case '-':
      zoomOut()
      break
  }
}

// Setup/cleanup
onMounted(() => {
  document.addEventListener('keydown', onKeyDown)
  document.addEventListener('mouseup', onMouseUp)
  document.addEventListener('mousemove', onMouseMove)
})

onUnmounted(() => {
  document.removeEventListener('keydown', onKeyDown)
  document.removeEventListener('mouseup', onMouseUp)
  document.removeEventListener('mousemove', onMouseMove)
})

// Watch for filter changes
watch(() => store.filteredGeoJSON, () => {
  currentIndex.value = 0
  resetView()
})

// Status color helper
const getStatusColor = (status) => {
  const colors = {
    'Sequenced': '#3b82f6',
    'Tissue Available': '#10b981',
    'Preserved Specimen': '#f59e0b',
    'Published': '#a855f7',
    'GBIF Record': '#6b7280',
    'Observation': '#6b7280',
    'Museum Specimen': '#8b5cf6',
    'Living Specimen': '#14b8a6'
  }
  return colors[status] || '#6b7280'
}
</script>

<template>
  <div class="image-gallery">
    <!-- Close button -->
    <button class="btn-close" @click="emit('close')">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <path d="M18 6 6 18M6 6l12 12"/>
      </svg>
    </button>

    <!-- Empty state -->
    <div v-if="specimensWithImages.length === 0" class="empty-state">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
        <rect x="3" y="3" width="18" height="18" rx="2" ry="2"/>
        <circle cx="8.5" cy="8.5" r="1.5"/>
        <polyline points="21 15 16 10 5 21"/>
      </svg>
      <h3>No Images Available</h3>
      <p>No specimens in the current filter have images attached.</p>
      <button class="btn-back" @click="emit('close')">Back to Map</button>
    </div>

    <!-- Main gallery -->
    <template v-else>
      <!-- Image viewer -->
      <div 
        ref="imageContainer"
        class="image-viewer"
        @mousedown="onMouseDown"
        @touchstart="onTouchStart"
        @touchmove="onTouchMove"
        @touchend="onTouchEnd"
        @wheel="onWheel"
        @dblclick="toggleZoom"
      >
        <!-- Loading spinner -->
        <div v-if="isLoading" class="image-loading">
          <div class="spinner"></div>
        </div>

        <!-- Error state -->
        <div v-else-if="loadError" class="image-error">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
            <circle cx="12" cy="12" r="10"/>
            <line x1="12" y1="8" x2="12" y2="12"/>
            <line x1="12" y1="16" x2="12.01" y2="16"/>
          </svg>
          <p>Failed to load image</p>
        </div>

        <!-- Image -->
        <img
          v-if="currentSpecimen?.image_url"
          ref="imageEl"
          :src="currentSpecimen.image_url"
          :alt="currentSpecimen.scientific_name"
          class="gallery-image"
          :class="{ zoomed: isZoomed }"
          :style="{
            transform: `scale(${zoomLevel}) translate(${panX / zoomLevel}px, ${panY / zoomLevel}px)`
          }"
          @load="onImageLoad"
          @error="onImageError"
          draggable="false"
        />
      </div>

      <!-- Info panel -->
      <div class="info-panel">
        <div class="info-content">
          <!-- Thumbnail (if enabled) -->
          <div v-if="store.showThumbnail && currentSpecimen?.image_url" class="info-thumbnail">
            <img
              :src="currentSpecimen.image_url"
              :alt="currentSpecimen.scientific_name"
            />
          </div>

          <!-- Specimen info -->
          <div class="specimen-info">
            <h3 class="species-name">
              <em>{{ currentSpecimen?.scientific_name }}</em>
              <span v-if="currentSpecimen?.subspecies" class="subspecies">
                {{ currentSpecimen.subspecies }}
              </span>
            </h3>
            <div class="specimen-meta">
              <span v-if="currentSpecimen?.id" class="meta-item">
                <strong>ID:</strong> {{ currentSpecimen.id }}
              </span>
              <span v-if="currentSpecimen?.sequencing_status" class="meta-item">
                <strong>Sequencing Status:</strong>
                <span class="status-badge" :style="{
                  backgroundColor: getStatusColor(currentSpecimen.sequencing_status),
                  color: '#fff',
                  padding: '2px 8px',
                  borderRadius: '4px',
                  fontSize: '0.75rem',
                  marginLeft: '4px'
                }">
                  {{ currentSpecimen.sequencing_status }}
                </span>
              </span>
              <span v-if="currentSpecimen?.mimicry_ring" class="meta-item">
                <strong>Mimicry:</strong> {{ currentSpecimen.mimicry_ring }}
              </span>
              <span v-if="currentSpecimen?.country" class="meta-item">
                <strong>Country:</strong> {{ currentSpecimen.country }}
              </span>
              <span v-if="currentSpecimen?.source" class="meta-item">
                <strong>Source:</strong> {{ currentSpecimen.source }}
              </span>
            </div>
          </div>
        </div>

        <!-- Counter -->
        <div class="image-counter">
          {{ currentIndex + 1 }} / {{ specimensWithImages.length }}
        </div>
      </div>

      <!-- Navigation arrows -->
      <button 
        class="nav-btn nav-prev" 
        :disabled="!hasPrev"
        @click="goToPrev"
      >
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="m15 18-6-6 6-6"/>
        </svg>
      </button>

      <button 
        class="nav-btn nav-next" 
        :disabled="!hasNext"
        @click="goToNext"
      >
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="m9 18 6-6-6-6"/>
        </svg>
      </button>

      <!-- Zoom controls -->
      <div class="zoom-controls">
        <button @click="zoomOut" :disabled="zoomLevel <= 1">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <circle cx="11" cy="11" r="8"/>
            <path d="m21 21-4.3-4.3"/>
            <line x1="8" y1="11" x2="14" y2="11"/>
          </svg>
        </button>
        <span class="zoom-level">{{ Math.round(zoomLevel * 100) }}%</span>
        <button @click="zoomIn" :disabled="zoomLevel >= 4">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <circle cx="11" cy="11" r="8"/>
            <path d="m21 21-4.3-4.3"/>
            <line x1="11" y1="8" x2="11" y2="14"/>
            <line x1="8" y1="11" x2="14" y2="11"/>
          </svg>
        </button>
      </div>

      <!-- Thumbnail strip -->
      <div class="thumbnail-strip" v-if="specimensWithImages.length > 1">
        <div class="thumbnail-scroll">
          <button
            v-for="(specimen, idx) in specimensWithImages.slice(0, 20)"
            :key="specimen.id"
            class="thumbnail"
            :class="{ active: idx === currentIndex }"
            @click="goToIndex(idx)"
          >
            <img 
              :src="specimen.image_url" 
              :alt="specimen.scientific_name"
              loading="lazy"
            />
          </button>
          <span v-if="specimensWithImages.length > 20" class="thumbnail-more">
            +{{ specimensWithImages.length - 20 }} more
          </span>
        </div>
      </div>
    </template>
  </div>
</template>

<style scoped>
.image-gallery {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.95);
  z-index: 2000;
  display: flex;
  flex-direction: column;
}

/* Close button */
.btn-close {
  position: absolute;
  top: 16px;
  right: 16px;
  width: 44px;
  height: 44px;
  background: rgba(255, 255, 255, 0.1);
  border: none;
  border-radius: 50%;
  color: #fff;
  cursor: pointer;
  transition: all 0.2s;
  z-index: 10;
  display: flex;
  align-items: center;
  justify-content: center;
}

.btn-close:hover {
  background: rgba(255, 255, 255, 0.2);
}

.btn-close svg {
  width: 24px;
  height: 24px;
}

/* Empty state */
.empty-state {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  color: #888;
  text-align: center;
  padding: 40px;
}

.empty-state svg {
  width: 80px;
  height: 80px;
  margin-bottom: 20px;
  opacity: 0.5;
}

.empty-state h3 {
  font-size: 1.5rem;
  color: #ccc;
  margin-bottom: 10px;
}

.empty-state p {
  font-size: 1rem;
  margin-bottom: 24px;
}

.btn-back {
  padding: 12px 24px;
  background: var(--color-accent, #4ade80);
  border: none;
  border-radius: 8px;
  color: #1a1a2e;
  font-size: 0.95rem;
  font-weight: 500;
  cursor: pointer;
}

/* Image viewer */
.image-viewer {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: hidden;
  cursor: grab;
  user-select: none;
}

.image-viewer:active {
  cursor: grabbing;
}

.gallery-image {
  max-width: 90%;
  max-height: 80vh;
  object-fit: contain;
  transition: transform 0.1s ease-out;
  will-change: transform;
}

.gallery-image.zoomed {
  cursor: move;
}

/* Loading */
.image-loading {
  display: flex;
  align-items: center;
  justify-content: center;
}

.image-loading .spinner {
  width: 50px;
  height: 50px;
  border: 3px solid rgba(255, 255, 255, 0.1);
  border-top-color: var(--color-accent, #4ade80);
  border-radius: 50%;
  animation: spin 1s linear infinite;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}

/* Error */
.image-error {
  display: flex;
  flex-direction: column;
  align-items: center;
  color: #888;
}

.image-error svg {
  width: 60px;
  height: 60px;
  margin-bottom: 12px;
}

/* Info panel */
.info-panel {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  padding: 16px 24px;
  background: rgba(0, 0, 0, 0.6);
  backdrop-filter: blur(10px);
}

.info-content {
  display: flex;
  align-items: flex-start;
  gap: 16px;
  flex: 1;
}

.info-thumbnail {
  flex-shrink: 0;
  width: 120px;
  height: 120px;
  border-radius: 8px;
  overflow: hidden;
  background: #333;
  border: 2px solid rgba(255, 255, 255, 0.1);
}

.info-thumbnail img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.specimen-info {
  flex: 1;
  min-width: 0;
}

.species-name {
  font-size: 1.2rem;
  font-weight: 600;
  color: #fff;
  margin: 0 0 6px 0;
}

.species-name em {
  color: var(--color-accent, #4ade80);
}

.subspecies {
  font-style: normal;
  font-weight: 400;
  color: #aaa;
  margin-left: 8px;
}

.specimen-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 16px;
}

.meta-item {
  font-size: 0.85rem;
  color: #888;
}

.meta-item strong {
  color: #aaa;
  font-weight: 500;
}

.image-counter {
  font-size: 0.9rem;
  color: #888;
  font-variant-numeric: tabular-nums;
}

/* Navigation buttons */
.nav-btn {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
  width: 50px;
  height: 80px;
  background: rgba(0, 0, 0, 0.4);
  border: none;
  color: #fff;
  cursor: pointer;
  transition: all 0.2s;
  display: flex;
  align-items: center;
  justify-content: center;
}

.nav-btn:hover:not(:disabled) {
  background: rgba(0, 0, 0, 0.6);
}

.nav-btn:disabled {
  opacity: 0.3;
  cursor: not-allowed;
}

.nav-btn svg {
  width: 30px;
  height: 30px;
}

.nav-prev {
  left: 0;
  border-radius: 0 8px 8px 0;
}

.nav-next {
  right: 0;
  border-radius: 8px 0 0 8px;
}

/* Zoom controls */
.zoom-controls {
  position: absolute;
  bottom: 140px;
  left: 50%;
  transform: translateX(-50%);
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 12px;
  background: rgba(0, 0, 0, 0.6);
  backdrop-filter: blur(10px);
  border-radius: 8px;
}

.zoom-controls button {
  width: 36px;
  height: 36px;
  background: rgba(255, 255, 255, 0.1);
  border: none;
  border-radius: 6px;
  color: #fff;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.2s;
}

.zoom-controls button:hover:not(:disabled) {
  background: rgba(255, 255, 255, 0.2);
}

.zoom-controls button:disabled {
  opacity: 0.3;
  cursor: not-allowed;
}

.zoom-controls button svg {
  width: 20px;
  height: 20px;
}

.zoom-level {
  font-size: 0.85rem;
  color: #aaa;
  min-width: 50px;
  text-align: center;
  font-variant-numeric: tabular-nums;
}

/* Thumbnail strip */
.thumbnail-strip {
  padding: 12px 24px;
  background: rgba(0, 0, 0, 0.6);
  border-top: 1px solid rgba(255, 255, 255, 0.1);
}

.thumbnail-scroll {
  display: flex;
  align-items: center;
  gap: 8px;
  overflow-x: auto;
  padding-bottom: 4px;
}

.thumbnail {
  flex-shrink: 0;
  width: 60px;
  height: 45px;
  padding: 0;
  background: #333;
  border: 2px solid transparent;
  border-radius: 4px;
  cursor: pointer;
  overflow: hidden;
  transition: all 0.2s;
}

.thumbnail:hover {
  border-color: rgba(255, 255, 255, 0.3);
}

.thumbnail.active {
  border-color: var(--color-accent, #4ade80);
}

.thumbnail img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.thumbnail-more {
  flex-shrink: 0;
  font-size: 0.8rem;
  color: #666;
  padding: 0 12px;
}

/* Scrollbar */
.thumbnail-scroll::-webkit-scrollbar {
  height: 6px;
}

.thumbnail-scroll::-webkit-scrollbar-track {
  background: rgba(255, 255, 255, 0.05);
  border-radius: 3px;
}

.thumbnail-scroll::-webkit-scrollbar-thumb {
  background: rgba(255, 255, 255, 0.2);
  border-radius: 3px;
}

/* Responsive */
@media (max-width: 768px) {
  .info-panel {
    flex-direction: column;
    align-items: flex-start;
    padding: 12px 16px;
  }

  .info-content {
    flex-direction: column;
    width: 100%;
  }

  .info-thumbnail {
    width: 100%;
    height: auto;
    aspect-ratio: 4/3;
  }

  .specimen-meta {
    gap: 10px;
  }

  .nav-btn {
    width: 40px;
    height: 60px;
  }

  .zoom-controls {
    bottom: 100px;
  }

  .thumbnail {
    width: 50px;
    height: 38px;
  }
}
</style>
